<a href="https://colab.research.google.com/github/bhagathkumar9494-gif/Ai-Powered-interview-platform/blob/main/ipl_data_set_analaysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

**Reading The Data**

In [4]:
df = pd.read_csv("/content/ball_by_ball_ipl.csv",index_col=0) # reading data from the csv file and index_col=0 tells the first column in data frame as a index column

**Various Functions**

In [ ]:
df.info() #displays the concise summary of data frame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 239693 entries, 0 to 239692
Data columns (total 35 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Unnamed: 0               239693 non-null  int64
 1   Match ID                 239693 non-null  int64
 2   Date                     239693 non-null  object
 3   Venue                    239693 non-null  object
 4   Bat First                239693 non-null  object
 5   Bat Second               239693 non-null  object
 6   Innings                  239693 non-null  int64
 7   Over                     239693 non-null  int64
 8   Ball                     239693 non-null  int64
 9   Batter                   239693 non-null  object
 10  Non Striker              239693 non-null  object
 11  Bowler                   239693 non-null  object
 12  Batter Runs              239693 non-null  int64
 13  Extra Runs               239693 non-null  int64
 14  Runs From Ball           239693 non-null  int64
 15  Ball Rebowled            239693 non-null  int64
 16  Extra Type               239693 non-null  object
 17  Wicket                   239693 non-null  int64
 18  Method                   11827 non-null   object
 19  Player Out               11827 non-null   object
 20  Innings Runs             239693 non-null  int64
 21  Innings Wickets          239693 non-null  int64
 22  Target Score             239693 non-null  int64
 23  Runs to Get              115766 non-null  float64
 24  Balls Remaining          239693 non-null  int64
 25  Winner                   239693 non-null  object
 26  Chased Successfully      239693 non-null  int64
 27  Total Batter Runs        239693 non-null  int64
 28  Total Non Striker Runs   239693 non-null  int64
 29  Batter Balls Faced       239693 non-null  int64
 30  Non Striker Balls Faced  239693 non-null  int64
 31  Player Out Runs          11827 non-null   float64
 32  Player Out Balls Faced   11827 non-null   float64
 33  Bowler Runs Conceded     239693 non-null  int64
 34  Valid Ball               239693 non-null  int64
dtypes: float64(3), int64(21), object(11)
memory usage: 64.0+ MB

In [5]:
df.shape # gives the total rows and columns as a touple

(239693, 34)

In [ ]:
df.dtypes #describes the data type of each column in a table

Unnamed: 0                   int64
Match ID                     int64
Date                        object
Venue                       object
Bat First                   object
Bat Second                  object
Innings                      int64
Over                         int64
Ball                         int64
Batter                      object
Non Striker                 object
Bowler                      object
Batter Runs                  int64
Extra Runs                   int64
Runs From Ball               int64
Ball Rebowled                int64
Extra Type                  object
Wicket                       int64
Method                      object
Player Out                  object
Innings Runs                 int64
Innings Wickets              int64
Target Score                 int64
Runs to Get                float64
Balls Remaining              int64
Winner                      object
Chased Successfully          int64
Total Batter Runs            int64
Total Non Striker Runs       int64
Batter Balls Faced           int64
Non Striker Balls Faced      int64
Player Out Runs            float64
Player Out Balls Faced     float64
Bowler Runs Conceded         int64
Valid Ball                   int64
dtype: object

In [ ]:
df.columns # describes the column names of a data frame

Index(['Unnamed: 0', 'Match ID', 'Date', 'Venue', 'Bat First', 'Bat Second',
       'Innings', 'Over', 'Ball', 'Batter', 'Non Striker', 'Bowler',
       'Batter Runs', 'Extra Runs', 'Runs From Ball', 'Ball Rebowled',
       'Extra Type', 'Wicket', 'Method', 'Player Out', 'Innings Runs',
       'Innings Wickets', 'Target Score', 'Runs to Get', 'Balls Remaining',
       'Winner', 'Chased Successfully', 'Total Batter Runs',
       'Total Non Striker Runs', 'Batter Balls Faced',
       'Non Striker Balls Faced', 'Player Out Runs', 'Player Out Balls Faced',
       'Bowler Runs Conceded', 'Valid Ball'],
      dtype='object')

In [ ]:
df.head() # describes the top 5 columns in a table

,Unnamed: 0,Match ID,Date,Venue,Bat First,Bat Second,Innings,Over,Ball,Batter,...,Winner,Chased Successfully,Total Batter Runs,Total Non Striker Runs,Batter Balls Faced,Non Striker Balls Faced,Player Out Runs,Player Out Balls Faced,Bowler Runs Conceded,Valid Ball
0,0,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,1,RD Gaikwad,...,Chennai Super Kings,0,4,0,1,0,NaN,NaN,4,1
1,1,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,2,RD Gaikwad,...,Chennai Super Kings,0,4,0,2,0,NaN,NaN,0,1
2,2,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,3,RD Gaikwad,...,Chennai Super Kings,0,4,0,3,0,NaN,NaN,0,1
3,3,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,4,RD Gaikwad,...,Chennai Super Kings,0,4,0,4,0,NaN,NaN,0,1
4,4,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,5,RD Gaikwad,...,Chennai Super Kings,0,5,0,5,0,NaN,NaN,1,1

In [ ]:
df.tail() #describe the bottom 5 columns in a table

,Unnamed: 0,Match ID,Date,Venue,Bat First,Bat Second,Innings,Over,Ball,Batter,...,Winner,Chased Successfully,Total Batter Runs,Total Non Striker Runs,Batter Balls Faced,Non Striker Balls Faced,Player Out Runs,Player Out Balls Faced,Bowler Runs Conceded,Valid Ball
239688,239688,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,1,YK Pathan,...,Sunrisers Hyderabad,1,16,31,9,29,NaN,NaN,2,1
239689,239689,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,2,YK Pathan,...,Sunrisers Hyderabad,1,22,31,10,29,NaN,NaN,6,1
239690,239690,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,3,YK Pathan,...,Sunrisers Hyderabad,1,26,31,11,29,NaN,NaN,4,1
239691,239691,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,4,YK Pathan,...,Sunrisers Hyderabad,1,27,31,12,29,NaN,NaN,1,1
239692,239692,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,5,KS Williamson,...,Sunrisers Hyderabad,1,32,27,30,12,NaN,NaN,1,1

**Data Cleaning**

In [ ]:
#df.isnull() or df.isna() handles the missing values
#dropna() removes the rows with missing values
#fillna(val) fill the missing values with some value called val
#duplicated() identifies the duplicates
#drop_duplicates() removes duplicate rows->option=(keep='first')=>keeps first occureance==>(keep='second')=>keeps the second occurance

In [9]:
catogorical_columns = df.select_dtypes(include=['object','category']).columns.tolist()
#select_dtypes is used to select all the columns in the with the specified data types => if we need only columns names do .columns and to to covert the names to list instead of object do .tolist()

In [12]:
df['Venue'].unique().tolist()

['Eden Gardens',
 'De Beers Diamond Oval',
 'Sharjah Cricket Stadium',
 'Wankhede Stadium',
 'Feroz Shah Kotla',
 'Holkar Cricket Stadium',
 'Punjab Cricket Association IS Bindra Stadium',
 'Maharashtra Cricket Association Stadium',
 'MA Chidambaram Stadium',
 'Dubai International Cricket Stadium',
 'Kingsmead',
 'Dr DY Patil Sports Academy',
 'SuperSport Park',
 'Sawai Mansingh Stadium',
 'Shaheed Veer Narayan Singh International Stadium',
 'M Chinnaswamy Stadium',
 'Rajiv Gandhi International Stadium',
 'Brabourne Stadium',
 'Sheikh Zayed Stadium',
 'M.Chinnaswamy Stadium',
 'Punjab Cricket Association Stadium',
 'Narendra Modi Stadium',
 'Arun Jaitley Stadium',
 'Barabati Stadium',
 'Saurashtra Cricket Association Stadium',
 'Sardar Patel Stadium',
 'Himachal Pradesh Cricket Association Stadium',
 'Nehru Stadium',
 'Green Park',
 'Subrata Roy Sahara Stadium',
 'JSCA International Stadium Complex',
 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
 'Zayed Cricket Stadium',
 'Vidarbha Cricket Association Stadium',
 "St George's Park",
 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium',
 'New Wanderers Stadium',
 'Newlands',
 'OUTsurance Oval',
 'Buffalo Park',
 'Barsapara Cricket Stadium']

In [13]:
 venue_map = {
     "M.Chinnaswamy Stadium": "M Chinnaswamy Stadium",
     "Sardar Patel Stadium": "Narendra Modi Stadium",
     "Punjab Cricket Association IS Bindra Stadium": "Punjab Cricket Association Stadium",
     "Feroz Shah Kotla": "Arun Jaitley Stadium",
     "Zayed Cricket Stadium": "Sheikh Zayed Stadium",
     "De Beers Diamond Oval": "Kimberley Oval",
     "Rajiv Gandhi International Stadium": "Uppal Stadium",
     "Dr Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium": "ACA-VDCA Stadium",
     "Shaheed Veer Narayan Singh International Stadium": "Raipur International Cricket Stadium",
     "JSCA International Stadium Complex": "Ranchi Stadium",
     "Barsapara Cricket Stadium": "Assam Cricket Association Stadium"
 }

 df['Venue'] = df['Venue'].replace(venue_map) #replace is used to replace each row value of specified column with new value

In [20]:
teamNameChange = {
     'Kings XI Punjab': 'Punjab Kings',
     'Delhi Daredevils': 'Delhi Capitals',
}
df['Bat First'] = df['Bat First'].replace(teamNameChange)
df['Bat Second'] = df['Bat Second'].replace(teamNameChange)
df['Winner'].unique().tolist()

['Chennai Super Kings',
 'Delhi Capitals',
 'Mumbai Indians',
 'Kings XI Punjab',
 'Kochi Tuskers Kerala',
 'Royal Challengers Bangalore',
 'Gujarat Titans',
 'Punjab Kings',
 'Kolkata Knight Riders',
 'Delhi Daredevils',
 'Pune Warriors',
 'Rajasthan Royals',
 'Sunrisers Hyderabad',
 'Lucknow Super Giants',
 'Deccan Chargers',
 'Gujarat Lions',
 'Rising Pune Supergiants',
 'Rising Pune Supergiant']

In [29]:
df['Batter']=df['Batter'].str.strip().str.title()
df['Non Striker'] = df['Non Striker'].str.strip().str.title()
df["Bowler"] = df["Bowler"].str.strip().str.title()
df["Player Out"] = df["Player Out"].str.strip().str.title()

In [ ]:
df.dropna()#used to remove rows with missing values

In [31]:
df.isna().sum() # used to know the number of missing values rows in each columns isna() gives boolean based on that 1,0 sum is calculated

Match ID                        0
Date                            0
Venue                           0
Bat First                       0
Bat Second                      0
Innings                         0
Over                            0
Ball                            0
Batter                          0
Non Striker                     0
Bowler                          0
Batter Runs                     0
Extra Runs                      0
Runs From Ball                  0
Ball Rebowled                   0
Extra Type                      0
Wicket                          0
Method                     227866
Player Out                 227866
Innings Runs                    0
Innings Wickets                 0
Target Score                    0
Runs to Get                123927
Balls Remaining                 0
Winner                          0
Chased Successfully             0
Total Batter Runs               0
Total Non Striker Runs          0
Batter Balls Faced              0
Non Striker Balls Faced         0
Player Out Runs            227866
Player Out Balls Faced     227866
Bowler Runs Conceded            0
Valid Ball                      0
dtype: int64

In [33]:
df['Method'].fillna('Not Out', inplace=True) # fillna() is used to fill the missing row values with some other values that we have provided and instead of assigning to column the current changed row the function has one more argument called inplace whose value by default is false in order too have a direct changes in the rows of particular coulmn make inplace=True
df['Player Out'].fillna('None', inplace=True)
df['Player Out Runs'].fillna(0, inplace=True)
df['Player Out Balls Faced'].fillna(0, inplace=True)
df['Runs to Get'].fillna(0, inplace=True)
df.isnull().sum()#cross verify if every coulmn has no missing values

Match ID                   0
Date                       0
Venue                      0
Bat First                  0
Bat Second                 0
Innings                    0
Over                       0
Ball                       0
Batter                     0
Non Striker                0
Bowler                     0
Batter Runs                0
Extra Runs                 0
Runs From Ball             0
Ball Rebowled              0
Extra Type                 0
Wicket                     0
Method                     0
Player Out                 0
Innings Runs               0
Innings Wickets            0
Target Score               0
Runs to Get                0
Balls Remaining            0
Winner                     0
Chased Successfully        0
Total Batter Runs          0
Total Non Striker Runs     0
Batter Balls Faced         0
Non Striker Balls Faced    0
Player Out Runs            0
Player Out Balls Faced     0
Bowler Runs Conceded       0
Valid Ball                 0
dtype: int64

In [35]:
#checking Duplicates
df.duplicated().sum() # return sum of total duplicate columns in a table np.int64(0) no duplicates

np.int64(0)